2020-08-17 11:11:55,013 INFO: Microblog startup [in C:\Users\David Martin\Desktop\microblog\microblog\app\__init__.py:43]
2020-08-17 11:12:34,075 INFO: Microblog startup [in C:\Users\David Martin\Desktop\microblog\microblog\app\__init__.py:43]
2020-08-17 11:19:53,114 INFO: Microblog startup [in C:\Users\David Martin\Desktop\microblog\microblog\app\__init__.py:43]
2020-08-17 12:37:39,460 INFO: Microblog startup [in C:\Users\David Martin\Desktop\microblog\microblog\app\__init__.py:43]
2020-08-17 12:54:12,150 INFO: Microblog startup [in C:\Users\David Martin\Desktop\microblog\microblog\app\__init__.py:43]
2020-08-17 12:54:27,951 INFO: Microblog startup [in C:\Users\David Martin\Desktop\microblog\microblog\app\__init__.py:43]
2020-08-17 12:54:37,970 INFO: Microblog startup [in C:\Users\David Martin\Desktop\microblog\microblog\app\__init__.py:43]
2020-08-17 13:41:02,742 INFO: Microblog startup [in C:\Users\David Martin\Desktop\microblog\microblog\app\__init__.py:43]
2020-08-17 14:08:45,172 INFO: Microblog startup [in C:\Users\David Martin\Desktop\microblog\microblog\app\__init__.py:43]
2020-08-17 14:08:51,268 ERROR: Exception on /user/steve [GET] [in c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\David Martin\Desktop\microblog\microblog\app\routes.py", line 85, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\David Martin\Desktop\microblog\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\David Martin\Desktop\microblog\microblog\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\David Martin\Desktop\microblog\microblog\app\templates\user.html", line 11, in block "content"
    <p>{{ user.follower.count() }} followers, {{ user.followed.count() }} following.</p>
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'follower'
2020-08-17 14:14:07,801 INFO: Microblog startup [in C:\Users\David Martin\Desktop\microblog\microblog\app\__init__.py:43]
2020-08-17 14:20:35,888 INFO: Microblog startup [in C:\Users\David Martin\Desktop\microblog\microblog\app\__init__.py:43]
2020-08-17 14:20:43,886 ERROR: Exception on /user/steve [GET] [in c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\David Martin\Desktop\microblog\microblog\app\routes.py", line 85, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\David Martin\Desktop\microblog\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\David Martin\Desktop\microblog\microblog\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\David Martin\Desktop\microblog\microblog\app\templates\user.html", line 11, in block "content"
    <p>{{ user.follower.count() }} followers, {{ user.followed.count() }} following.</p>
  File "c:\users\david martin\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'follower'
2020-08-17 14:34:28,639 INFO: Microblog startup [in C:\Users\David Martin\Desktop\microblog\microblog\app\__init__.py:43]
